openapi: 3.0.0
info:
  description: Your API Description here
  version: 1.0.0
  title: API Docs Title
servers:
  - url: /api # The base path of each route

paths:
  /users:
    $ref: "./paths/users.yaml"
